### ISSUE TITLE
Add pure

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/static-analysis#1025]
We should add https://github.com/ronomon/pure to the list.
Pull requests very welcome. 😊
If you like to contribute to the project, please check out [CONTRIBUTING.md](https://github.com/analysis-tools-dev/static-analysis/blob/master/CONTRIBUTING.md) to get started.

@jorangreef fyi

**Comment by mre** [comment]
https://github.com/analysis-tools-dev/static-analysis/pull/1072

**Comment by jorangreef** [comment]
Thanks @mre !
