### ISSUE TITLE
Add GCC

### ISSUE THREAD

**Issue by amitdo** [analysis-tools-dev/static-analysis#1150]
- [GCC](https://gcc.gnu.org/) — The GCC compiler has [static analysis capabilities](https://gcc.gnu.org/onlinedocs/gcc/Static-Analyzer-Options.html) since version 10.

**Comment by mre** [comment]
Great idea. Never considered GCC, but it make sense. Thanks for the suggstion @amitdo.

**Comment by amitdo** [comment]
You're welcome :-)

BTW, the next version of GCC (v13), will have an option to output its (static and dynamic) diagnostics to a json file that uses the SARIF format.

**Comment by mre** [comment]
Merged #1153 🎉 Thanks again for the suggestion.
