### ISSUE TITLE
Looks like CI builds are failing

### ISSUE THREAD

**Issue by jayu** [analysis-tools-dev/static-analysis#1161]
Hey, it looks like CI builds are failing since 13 Dec.

Two added tools were not deployed to `https://analysis-tools.dev/` 

Looks like some config is missing [Job link](https://github.com/analysis-tools-dev/static-analysis/actions/runs/3685045125/jobs/6235512912)

![image](https://user-images.githubusercontent.com/11561585/209465507-c5269f11-899d-4127-ba87-e43c5932942f.png)

![image](https://user-images.githubusercontent.com/11561585/209465516-a5cb1c0e-7d98-4c62-8c42-c885888c9e07.png)

**Comment by mre** [comment]
Thanks for the report. It's fixed now. The reason was an outdated Github token.
