### ISSUE TITLE
clang-tidy vs. scan-build

### ISSUE THREAD

**Issue by exoosh** [analysis-tools-dev/static-analysis#1212]
Hi,

https://analysis-tools.dev/tag/cpp lists `clang-tidy` with the description:

> clang static analyser.

That is wrong. It's a "linter" and the tool itself as well as its authors describe it as such (your site categorizes it that way as well). It shares some checks with the Clang Static Analyzer, but it isn't the same.

The Clang Static Analyzer is built into the compiler and `scan-build` can be used to drive the compiler in a way that the CSA yields results.

With best regards,

Oliver

PS: also [KLEE](https://klee.github.io/) seems to be missing.

**Comment by mre** [comment]
Hi Oliver,
it is a bit hard for me to understand what exactly you'd like to have changed. 
The files for scan-build and clang-tidy are here:
* https://github.com/analysis-tools-dev/static-analysis/blob/master/data/tools/scan-build.yml
* https://github.com/analysis-tools-dev/static-analysis/blob/master/data/tools/clang-tidy.yml

You can propose a change by editing the files and opening a pull request.
Thanks for metioning KLEE. I'd appreciate a pull request to have it added to the list. 👍
