### ISSUE TITLE
CppDepend still shown as deprecated

### ISSUE THREAD

**Issue by CoderGears** [analysis-tools-dev/static-analysis#1307]
The cppdepend.yml were changed and commited to remove the deprecated flag. However in the Readme the deprecated flag still there.

**Comment by mre** [comment]
There was a bug in a pipeline, where checked the `deprecated` boolean for existence, but not for `true.
https://github.com/analysis-tools-dev/static-analysis/commit/59c0f96384c1322b526d67f45950822e211c6154
It's resolved now; sorry for the inconvenience.
