### ISSUE TITLE
Many links in the table of contents are not working

### ISSUE THREAD

**Issue by Delgan** [analysis-tools-dev/static-analysis#1439]
Hi.

Some links in the table of contents are broken, for example:
* [C++](https://github.com/analysis-tools-dev/static-analysis#cpp)
* [.env](https://github.com/analysis-tools-dev/static-analysis#dotenv)
* [Configuration Management](https://github.com/analysis-tools-dev/static-analysis#configmanagement)

This is because the anchor link generated for "C++" isn't "cpp" but "c-2".

**Comment by mre** [comment]
Hm! Thanks for the heads-up.
Would you be able to create a pull request to fix those? That would be highly appreciated. 🙏 
Moreover, we should be able to detect future breakage once I find the time to release a new version of lychee, which now supports [anchor tags in Markdown](https://github.com/lycheeverse/lychee/pull/1126).

**Comment by Delgan** [comment]
Hmm... To be fair, I'm not even sure about how to properly fix it.

The links in the Readme are generated from your data files. A title is generated with:

```html
<h2 id="{{ tag.value }}">{{ tag.name }}</h2>
```

We could expect `#cpp` anchor to redirect to this section, but this is not the case because Github suppress your `id` with their own anchor link (`#c-2` in this case).

**Comment by mre** [comment]
Why would the custom tags be surpressed? Isn't that the idea behind custom tags?

**Comment by Delgan** [comment]
> Why would the custom tags be surpressed? Isn't that the idea behind custom tags?

I don't know, you'd have to ask Github folks, not me. :smile: 

In the Readme.md raw we can see:

```html
<h2 id="cpp">C++</h2>
```

However, once rendered By Github, in the DOM it becomes:

```html
<h2 id="user-content-c-2" tabindex="-1" dir="auto">
    <a class="heading-link" href="#c-2">
    C++
    <svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"></svg>
    </a>
</h2>
```

But it gets worse: they've re-implemented anchoring in Javascript. That means `#c-2` in the URL doesn't work with Javascript disabled, since the `id` attribute is `"user-content-c-2"` and not `"c-2"`.

**Comment by mre** [comment]
Oh wow. That's pretty bad. We could add a condition for certain tags to the template, but apart from that I'm out of ideas here.

**Comment by Delgan** [comment]
Other possible alternatives:
* Replace `[{{ tag.name }}](#{{ tag.value }})` in the template with a function that copy Github's automatic anchor generation (I guess the process is 1. lowercasing, 2. replacing spaces with dashes, 3. removing non-alphanumeric characters, 4. deduplicating).
* Remove the manually created table of contents and let users discover the one built-in by GitHub (the button at the top-left of the Readme).
* Ask Github to fix it (don't suppress `id` if it exists) or to implement [`Heading IDs`](https://www.markdownguide.org/extended-syntax/#heading-ids) syntax.

**Comment by mre** [comment]
Oh, right, that's true. These are all good options I haven't seen. 

For Option 1, don't we need to keep track of the "count", too? E.g. in your example, it is `c-2`. Presumably, because the label occurs more than once. It also sounds like additional maintenance work.

We could also keep the table of contents and just remove the broken entries. Probably not satisfactory.

The built-in table of contents sounds good, too. Less discoverable, though. 

So far, all solutions have their drawbacks. But yeah, removing the table of contents sounds like the most reasonable option right now.

**Comment by Delgan** [comment]
> For Option 1, don't we need to keep track of the "count", too? E.g. in your example, it is `c-2`. Presumably, because the label occurs more than once. It also sounds like additional maintenance work.

Yes, that what I meant by "deduplicating". But the whole thing is definitely not very elegant.



> The built-in table of contents sounds good, too. Less discoverable, though.
> 
> So far, all solutions have their drawbacks. But yeah, removing the table of contents sounds like the most reasonable option right now.

Yeah, I like the table of content as part of the Readme, but it seems Github doesn't...

As per [this discussion](https://github.com/orgs/community/discussions/60861) it seems there exists a possible workaround, though. If the `<h2>` is prepended with `<a name="cpp"></a>` it seems anchoring with `#cpp` will work. Seem demo [here](https://github.com/Delgan/static-analysis/tree/patch-1#readme).

**Comment by mre** [comment]
Ah, nice!

Then we could update the template accordingly.

This will work then:

```html
<a name="cpp" />
<h2 id="cpp">C++</h2>
```

Maybe even this?

```
<a name="cpp" />
<h2>C++</h2>
```

Then it's slightly less readable, but correct.
Thanks for all the research! No clue how you found that.
Would you be able to create a PR for that? ❤️

**Comment by Delgan** [comment]
@mre Sure, I created #1451. Let see if it renders well. :)
