### ISSUE TITLE
vera++ appaers to be inactive

### ISSUE THREAD

**Issue by hexagonrecursion** [analysis-tools-dev/static-analysis#1607]
* [According to the wiki the latest release is Vera 1.3.0 2015-01-22](https://bitbucket.org/verateam/vera/wiki/Home)
* [The latest commit on master is 2020-07-28](https://bitbucket.org/verateam/vera/commits/branch/master)

**Comment by mre** [comment]
Okay. Can you create a pull request to mark it as deprecated similar to this? https://github.com/analysis-tools-dev/static-analysis/pull/1603
