### ISSUE TITLE
Remove outdated tools; fix links

### ISSUE THREAD

**Issue by mre** [analysis-tools-dev/static-analysis#1625]
I noticed that some links were broken. This could mean that the website has changed or that the project got removed from the web. In any case, we should remove the unavailable tools and fix the broken links.

For the failing links, check out the tools in https://github.com/analysis-tools-dev/static-analysis/tree/master/data/tools and fix the links there. For removed projects, simply delete the entire YAML file in the same folder.
Pull requests welcome!

### Errors in README.md

* [404] [https://mangothecat.github.io/goodpractice](https://mangothecat.github.io/goodpractice) | Failed: Network error: Not Found
Error: R] [https://coala.io/](https://coala.io/) | Failed: Network error: error sending request for url (https://coala.io/)
* [404] [https://bitbucket.org/yanniss/doop](https://bitbucket.org/yanniss/doop) | Failed: Network error: Not Found
Error: R] [https://ruby.sadi.st/Flog.html](https://ruby.sadi.st/Flog.html) | Failed: Network error: error sending request for url (https://ruby.sadi.st/Flog.html)
Error: R] [https://pycodequ.al/](https://pycodequ.al/) | Failed: Network error: error sending request for url (https://pycodequ.al/)
* [404] [https://www.synopsys.com/software-integrity/security-testing/static-analysis-sast.html](https://www.synopsys.com/software-integrity/security-testing/static-analysis-sast.html) | Failed: Network error: Not Found
Error: R] [https://ruby.sadi.st/Flay.html](https://ruby.sadi.st/Flay.html) | Failed: Network error: error sending request for url (https://ruby.sadi.st/Flay.html)
Error: R] [https://www.exakat.io/](https://www.exakat.io/) | Failed: Network error: error sending request for url (https://www.exakat.io/)
* [TIMEOUT] [https://packj.dev/](https://packj.dev/) | Timeout
* [403] [https://www.whitehatsec.com/platform/static-application-security-testing](https://www.whitehatsec.com/platform/static-application-security-testing) | Failed: Network error: Forbidden
Error: R] [https://nitpick-ci.com/](https://nitpick-ci.com/) | Failed: Network error: error sending request for url (https://nitpick-ci.com/)
Error: R] [https://www.lunasec.io/](https://www.lunasec.io/) | Failed: Network error: error sending request for url (https://www.lunasec.io/)
* [TIMEOUT] [https://www.qualys.com/apps/container-security](https://www.qualys.com/apps/container-security) | Timeout
* [404] [http://oclint.org/](http://oclint.org/) | Failed: Network error: Not Found
Error: R] [http://code.yorickpeterse.com/ruby-lint/latest](http://code.yorickpeterse.com/ruby-lint/latest) | Failed: Network error: error sending request for url (http://code.yorickpeterse.com/ruby-lint/latest)
Error: R] [https://coala.io/languages](https://coala.io/languages) | Failed: Network error: error sending request for url (https://coala.io/languages)
* [404] [http://tools.android.com/tips/lint](http://tools.android.com/tips/lint) | Failed: Network error: Not Found

**Comment by kat-kan** [comment]
Hi, I'd like to work on this issue

**Comment by mre** [comment]
Sure, thanks! Go ahead and send pull requests. Take a look into the contributing guidelines to get an overview: https://github.com/analysis-tools-dev/static-analysis/blob/master/CONTRIBUTING.md
