### ISSUE TITLE
list of open source writing assistance and english linting tools 

### ISSUE THREAD

**Issue by Foadsf** [analysis-tools-dev/static-analysis#216]
Thanks for the great list. [Here ](https://www.quora.com/Are-there-any-free-alternatives-to-Grammarly-software/answer/Foad-S-Farimani?ch=2&srid=iETG)I have listed other available writing assistance tools, and [here ](https://www.reddit.com/r/opensource/comments/8xgldr/any_freeopensource_software_for_plagiarism/)some of the available plagiarism checker tools. There are also other linting tools available:

- [alex](https://github.com/get-alex/alex)
- [Just Say No](https://atom.io/packages/linter-just-say-no)
- [textlint](https://textlint.github.io/)
- [Coala](https://coala.io/#/home?lang=Python)
- [Aspelllint](https://github.com/mcandre/aspelllint)
- [anorack](http://jwilk.net/software/anorack)
- [Joblint](https://github.com/rowanmanning/joblint)

**Comment by mre** [comment]
Hey @Foadsf,
that's indeed a great list of tools.
Would you mind creating a pull request to add them to the writing section? https://github.com/mre/awesome-static-analysis#writing

**Comment by mre** [comment]
Forgot to mention that there is a guideline for the format of each tool [here](https://github.com/mre/awesome-static-analysis/blob/master/CONTRIBUTING.md)

**Comment by Foadsf** [comment]
@mre Sure, There are actually way more. I'm working on a complete list. I will put them here and if work allows I will send a PR.

**Comment by Foadsf** [comment]
lets my complete list lay here for the moment:



- Diction --> https://www.gnu.org/software/diction/
- style-check.rb --> http://www.cs.umd.edu/~nspring/software/style-check-readme.html
- aspell --> http://www.physics.usyd.edu.au/guides/spell-grammar-latex.html
- Ispell --> https://www.cs.hmc.edu/~geoff/ispell.html
- Hunspell  --> http://hunspell.github.io/
- yaspeller --> https://github.com/hcodes/yaspeller
- retext  --> https://github.com/retextjs/retext
- GitBook  --> https://www.gitbook.com/
- Lightproof editor --> https://extensions.libreoffice.org/extensions/lightproof-editor
- After the Deadline --> http://www.afterthedeadline.com/
- Link Grammar Parser for AbiWord --> https://www.abisource.com/projects/link-grammar/
- Queequeg --> http://queequeg.sourceforge.net/index-e.html
- GRAC: GRAmmar Checker --> http://grac.sourceforge.net/
- Aiksaurus --> http://aiksaurus.sourceforge.net/

**Comment by mre** [comment]
Impressive. Would be very happy to merge those indeed.
We'd just have to check that each tool is actively maintained. Also if they are copyrighted, we would have to add a :copyright: emoji. But all that info is already in the contributing file. :wink:

**Comment by Foadsf** [comment]
- Not sure what do you mean by copywrited. They all should have their own Free and Open Source license. deducing their license to a C marking doesn't seem like a good idea to me.
- being maintained is a rather subjective qualification. Maybe need some metrics? like last updates, contributes, open issues..
- Maybe Repology statistics including the latest versions, package managers, repositories ... could be somehow integrated

**Comment by mre** [comment]
> Not sure what do you mean by copywrited. They all should have their own Free and Open Source license. deducing their license to a C marking doesn't seem like a good idea to me.
Ah okay, that's fine then. :+1: 

> being maintained is a rather subjective qualification.
That's true. There is no real metric for that. Just like to keep the list up-to-date. From a first glance, the tools you mentioned should all be actively maintained.

> Maybe Repology statistics including the latest versions, package managers, repositories ... could be somehow integrated.
Yeah, I thought about that, too but I'd do that in a separate pull request to keep things simple for now. In the long run, there might be a CI bot, which pushes and updates these statistics on a regular basis.

**Comment by chadbrewbaker** [comment]
@Foadsf Some of the commercial/hosted English linters. Tempted to write a Webdriver script around some of the free online form based tools.

Is there a good corpus of English language defects? Curious to compare them all. I bet many of the commercial tools are using open source tools behind the scenes.

Grammar Lookup -> https://www.grammarlookup.com
Grammarly -> https://app.grammarly.com
Sentence Checkup -> https://sentencecheckup.com
Hemmingway -> http://www.hemingwayapp.com
White Smoke -> http://www.whitesmoke.com

**Comment by mre** [comment]
@Foadsf, @chadbrewbaker are you planning to revisit these tools in the near future? Otherwise I would be closing this to keep the issue tracker clean and tidy. 😊
