### ISSUE TITLE
Markdown not completely rendered

### ISSUE THREAD

**Issue by DanielRuf** [analysis-tools-dev/static-analysis#248]
At least `:warning:`, `:copyright:` and so on are not rendered on the website.

**Comment by mre** [comment]
That is true indeed. Thanks for the info. I think we should fix that at some point. Was considering to move away from `mkdocs` at some point and start a proper website for the tools.

**Comment by mre** [comment]
Just a quick update on that, @DanielRuf:
It should be working fine on the new website now. [Here's an example](https://analysis-tools.dev/tool/cppdepend). Thanks for the report. ❤️
