### ISSUE TITLE
Are these tools awesome?

### ISSUE THREAD

**Issue by nvhaver** [analysis-tools-dev/static-analysis#281]
I started compiling a list of SAST tools as part of a research assignment, only to stumble upon this awesome list. I noted that several of the tools I found are not yet listed, however I have no idea whether the tools I found are 'awesome'... For some of them I could find some objective proof (e.g. the Gartner Magic Quadrant for SAST tools), and so I created some PRs already.

### PRs created for:
- AppScan Source HCL #277 
- WhiteHat Sentinel Source #279 
- Synopsys Coverity #280 
- Checkmarx CxSAST #278 

### Not sure if awesome:
- [Appknox](https://www.appknox.com/products) (Online scanner)
- [bugScout](https://bugscout.io/en/source-code-analyzer/) (multiple languages such as Java, PHP, .NET and classic ASP)
- [Code Dx Enterprise](https://codedx.com/code-dx-enterprise/) (Correlation engine bundled with SAST/DAST/IAST/other tools)
- [Devknox](https://devknox.io/) (Android, will become open source soon, no longer supported officially)
- [Jtest](https://www.parasoft.com/products/jtest) (Java)
- [Ripstech](https://www.ripstech.com/)
- [Snappy Tick](https://snappycodeaudit.com/)
- [Sparrow SAST](http://sparrowfasoo.com/product/sast) (Support over 20 languages including Java, JSP, C/C++, C#, Python, Swift, ASP(.NET), ABAP, Object C, etc)
- [ThunderScan](https://www.defensecode.com/thunderscan.php) (Multilanguage)
- [TrueCode](https://www.palcomonline.com/sitelock-security/truecode-static-application-security-testing/)
- [Virtual Forge Security Suite](https://www.virtualforge.com/en/security-suite) (SAP)
- [VisualCodeGrepper](https://github.com/nccgroup/VCG) (VCG is an automated code security review tool that handles C/C++, Java, C#, VB and PL/SQL)
- [Xanitizer]() (Java/Scala)
- [ZeroNorth](https://www.zeronorth.io/product/)

Any feedback on the above tools is welcome. If any of the tools is found to be awesome, let me know and I will create PRs.

**Comment by mre** [comment]
First off, YOU are awesome. So many great updates make me smile. 😊 

All the tools look great and I would accept PRs for them.
The single exception might be VisualCodeGrepper, which hasn't seen any updates since 2016 and only has one contributor.

Reviewing PaaS tools is hard, because the websites usually look nice, but that doesn't say much about the maintenance status of the tool. Usually I give them the benefit of the doubt until a tool gets [marked deprecated](https://github.com/mre/awesome-static-analysis/blob/master/CONTRIBUTING.md#how-to-mark-a-tool-as-unmaintaineddeprecated).

So please go ahead and create the pull requests if you like. Thanks 💯 for the ones you already created.

**Comment by mre** [comment]
Ping @nvhaver. Maybe you find the time to do this PR for Hacktoberfest? 😃

**Comment by normanwenzel** [comment]
> First off, YOU are awesome. So many great updates make me smile. 😊
> 
> All the tools look great and I would accept PRs for them.
> The single exception might be VisualCodeGrepper, which hasn't seen any updates since 2016 and only has one contributor.
> 
> Reviewing PaaS tools is hard, because the websites usually look nice, but that doesn't say much about the maintenance status of the tool. Usually I give them the benefit of the doubt until a tool gets [marked deprecated](https://github.com/mre/awesome-static-analysis/blob/master/CONTRIBUTING.md#how-to-mark-a-tool-as-unmaintaineddeprecated).
> 
> So please go ahead and create the pull requests if you like. Thanks 💯 for the ones you already created.

Dear Matthias, dear Nick, I am one of the founders of RIGS IT, the vendor of Xanitizer. Please let me know if you have any questions about the tool to decide if it is worth a PR. Best regards, Norman

**Comment by mre** [comment]
Hey @normanwenzel,
yeah Xanitizer would be a great fit for the list. Can you create a PR?

**Comment by normanwenzel** [comment]
> Hey @normanwenzel,
> yeah Xanitizer would be a great fit for the list. Can you create a PR?

DONE

**Comment by mre** [comment]
@nvhaver do we want to add more tools to the list or can we close this for now?
