### ISSUE TITLE
IDEA Inspection plugin

### ISSUE THREAD

**Issue by Mkohm** [analysis-tools-dev/static-analysis#295]
https://github.com/JetBrains/inspection-plugin can be used in Java, Kotlin and Android projects and includes all the inspections that are available in the IntelliJ IDE.  Where is the appropriate section for this tool? 

It is applied to any gradle project, so i guess the Multiple languages section would be appropriate?

**Comment by mre** [comment]
@Mkohm, yeah I agree. That would be a good fit. Care to whip up a PR? 😊 Sorry for the late reply.
