### ISSUE TITLE
Possible Suggestion: Add star count to github projects

### ISSUE THREAD

**Issue by Amar1729** [analysis-tools-dev/static-analysis#327]
This is a great resource for a lot of tools that a reader may not initially be familiar with. However, deciding what to use can get a little difficult without a sense of what's popular in the community. One metric (not saying it's the only one) of determining the "popularity" of a tool is the star count of the associated github repo - e.g.

* ![GitHub stars](https://img.shields.io/github/stars/PyCQA/bandit?style=social) [bandit](https://github.com/PyCQA/bandit) - a tool to find common security issues in Python code
* ![GitHub stars](https://img.shields.io/github/stars/psf/black?style=social) [black](https://github.com/psf/black) - The uncompromising Python code formatter

I wouldn't want to imply one is better than the other in this case, but I think counts like this may provide helpful information for someone new to a language/these tools trying to decide what to use.

If there's interest in this I could submit a PR adding some type of badge to the lines that are github links?

**Comment by mre** [comment]
This is a great idea! More visibility is always good to make an informed decision. I'm a bit worried the badges might be visually quite distracting. If you like, you could send a PR for a single section so that we can see how it looks like.

**Comment by Amar1729** [comment]
not stale - my bad, this had slipped my mind until just now.

**Comment by mre** [comment]
Weird that this issue was closed by the bot, even though there clearly was new activity... 🤔
