### ISSUE TITLE
Add Java tools

### ISSUE THREAD

**Issue by brunoborges** [analysis-tools-dev/static-analysis#500]
Any particular reason Java tools are not listed?

**Comment by mre** [comment]
Huh? Where exactly?
Can see them on the list [here](https://github.com/analysis-tools-dev/static-analysis#java) and on the website [here](https://analysis-tools.dev/tag/java).

**Comment by brunoborges** [comment]
From the front page [1], a user can't realize that Java - or any other language but Python, Ruby, PHP, C, Javascript, and Go - is catalogued at all. 

I'd also be curious to learn what criteria or motivation the team had for selecting these 6 languages, but something really just out of curiosity.

![Screen Shot 2020-08-20 at 3 59 03 PM](https://user-images.githubusercontent.com/129743/90834008-19c2f880-e2fe-11ea-9166-e5557cc11664.png)

[1] https://analysis-tools.dev/

**Comment by mre** [comment]
Moved the "show more" button below the other languages to make it more prominent.
<img width="844" alt="image" src="https://user-images.githubusercontent.com/175809/91345699-0f15d100-e7e0-11ea-8ad2-e6943de248ed.png">

**Comment by brunoborges** [comment]
Ah, that's better. Thanks for the quick fix!

And out of curiosity, what criteria was used to list these 6 languages? What criteria was used to select them as the "Popular Languages" ?

**Comment by mre** [comment]
Honestly there wasn't much of a thought process.
We just picked an iconset we liked (linked in the footer) and it happened to have those language icons in them.
The rest was just a rough orientation on the [TIOBE index](https://www.tiobe.com/tiobe-index/) while keeping an eye on the number of tools we list. 
I added Java and C# to the homepage now. 😉 
Guess we can close this.
