### ISSUE TITLE
Wrong slug name

### ISSUE THREAD

**Issue by hakancelik96** [analysis-tools-dev/static-analysis#544]
If there are two tools with the same name, they are directed to the same address for example unimport from GO lang and Python lang.

**Comment by mre** [comment]
Oh, that's bad. Thanks for the heads-up @hakancelik96. One way to avoid it would be adding an additional "slug" field to resolve the ambiguity. I'd like to avoid adding another bit of information (like the programming language) to the URL as it would make the URL longer for all entries and is not be sufficient in all cases (e.g. when a tool with the same name exists for the same language). Alternative ideas welcome.
